- name: zabbix agent configuration
  hosts: all
  become: yes
  vars:
    zabbix_server_ip: "your_zabbix_server_ip"
    zabbix_agent_config_path: "/etc/zabbix/zabbix_agentd.conf"

  tasks:
    - name: zabbix repository configuration
      apt:
        deb: "http://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu20.04_all.deb"
        state: present
        update_cache: no

    - name: install zabbix agent
      apt:
        name: zabbix-agent
        state: present
        update_cache: no
    - name: configure zabbix agent
      lineinfile:
        path: "{{ zabbix_agent_config_path }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^Server=', line: "Server={{ zabbix_server_ip }}" }
        - { regexp: '^ServerActive=', line: "ServerActive={{ zabbix_server_ip }}" }
        - { regexp: '^Hostname=', line: "Hostname={{ inventory_hostname }}" }

    - name: ensure zabbix agent is enabled
      service:
        name: zabbix-agent
        state: started
        enabled: yes

    - name: restart zabbix agent
      service:
        name: zabbix-agent
        state: restarted
