---
- name: installing gitlab-server
  hosts: gitlab_servers
  connection: local
  become: yes
  tasks:
    - name: packages update
      apt:
        update_cache: yes
        upgrade: dist

    - name: packages installation
      apt:
        name: 
          - ca-certificates
          - curl
          - openssh-server
          - tzdata
        state: present

    - name: add gitlab repo
      apt_key:
        url: https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
        state: present

    - name: add gitlab repo
      apt_repository:
        repo: 'deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ focal main'
        state: present

    - name: install gitlab
      apt:
        name: gitlab-ce
        state: present

    - name: configure gitlab
      template:
        src: gitlab.rb
        dest: /etc/gitlab/gitlab.rb
        owner: root
        group: root
        mode: 0644
      notify:
        - reconfigure gitlab

  handlers:
    - name: reconfigure GitLab
      command: /opt/gitlab/bin/gitlab-ctl reconfigure
